config/routes.rb
Tpprd::Application.routes.draw do

  resources :header_images

  resources :hrader_images

  resources :quotations

  resources :image_albums

  resources :image_galleries

  post '/rate' => 'rater#create', :as => 'rate'
  resources :service_lists

  get "navigations/news_show"
  get "navigations/news"
  get "navigations/gallery"
  get "navigations/albums"
  get "navigations/previews"
  get "navigations/preview_show"
  get "navigations/events"
  get "navigations/event_show"
  get "navigations/quotations"
  get "navigations/quotations_show"

=begin
  get "service/f_t_contracts"
  get "service/b_e_a_t"
  get "service/e_i_c_c"
  get "service/i_and_i"
  get "service/mediation"
  get "service/org_department"
  get "service/translations"
  get "service/legal_support"
  get "service/arbitral_tribunal"
=end
  resources :static_texts

  resources :service

  devise_for :users

  resources :contests

  resources :departments

  resources :people

  resources :events

  resources :previews

  get "about/index"
  get "about/info"

  get "administration/index"
  get "administration/localization"
  get "members_tpp/how_become"
  get "members_tpp/docs"
  resources :news
  mount Ckeditor::Engine => '/ckeditor'

  get "service/f_e_activity"

   root 'about#index'

   get 'administration/index', as: 'user_root'

  

end

app/models/contest.rb
class Contest < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/header_image.rb
class HeaderImage < ActiveRecord::Base

  do_not_validate_attachment_file_type :avatar
  has_attached_file :avatar, :styles => { :medium => "1076x274>", :thumb => "100x100>" }

end

app/models/image_album.rb
class ImageAlbum < ActiveRecord::Base
  has_many :image_gallery
end

app/models/image_gallery.rb
class ImageGallery < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/models/localization.rb
class Localization < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base

end

app/models/person.rb
class Person < ActiveRecord::Base

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/preview.rb
class Preview < ActiveRecord::Base
end

app/models/quotation.rb
class Quotation < ActiveRecord::Base
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "News"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/service_list.rb
class ServiceList < ActiveRecord::Base
end

app/models/static_text.rb
class StaticText < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    render :layout =>  "../administration/index"

  end

  # GET /people/1
  # GET /people/1.json
  def show

    render :layout =>  "../administration/index"

  end

  # GET /people/new
  def new
    @person = Person.new

    render :layout =>  "../administration/index"

  end

  # GET /people/1/edit
  def edit

    render :layout =>  "../administration/index"

  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @person }
      else
        format.html { render action: 'new' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :last_name, :patronymic, :description, :avatar)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/views/people/_form.html.erb
<%= form_for(@person ,  :html => { :multipart => true } ) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Имя %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Фамилия %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :Отчество %><br>
    <%= f.text_field :patronymic %>
  </div>
  <div class="field">
    <%= f.label :Описание %><br>
    <%= f.cktext_area :description, :as => :ckeditor %>
  </div>
  <div class="field">
    <%= f.label :Аватар %><br>
    <%=f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Люди</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Имя</th>
      <th>Фамилия</th>
      <th>Отчество</th>
      <th>Описание</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.last_name %></td>
        <td><%= person.patronymic %></td>
        <td><%= person.description %></td>
        <td><%= link_to 'Показать', person %></td>
        <td><%= link_to 'Изменить', edit_person_path(person) %></td>
        <td><%= link_to 'Удалить', person, method: :delete, data: { confirm: 'Вы уверенны?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Создать', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Аватар:</strong>
<div class="col-xs-6 col-sm-3 placeholder">
  <img src="<%= @person.avatar.url(:medium) %>" class="img-responsive" alt="Generic placeholder thumbnail"/>
    </div>
</p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @person.last_name %>
</p>

<p>
  <strong>Patronymic:</strong>
  <%= @person.patronymic %>
</p>

<p>
  <strong>Description:</strong>
  <%= @person.description %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>