config/routes.rb
Tpprd::Application.routes.draw do

  resources :header_images

  resources :hrader_images

  resources :quotations

  resources :image_albums

  resources :image_galleries

  post '/rate' => 'rater#create', :as => 'rate'
  resources :service_lists

  get "navigations/news_show"
  get "navigations/news"
  get "navigations/gallery"
  get "navigations/albums"
  get "navigations/previews"
  get "navigations/preview_show"
  get "navigations/events"
  get "navigations/event_show"
  get "navigations/quotations"
  get "navigations/quotations_show"

=begin
  get "service/f_t_contracts"
  get "service/b_e_a_t"
  get "service/e_i_c_c"
  get "service/i_and_i"
  get "service/mediation"
  get "service/org_department"
  get "service/translations"
  get "service/legal_support"
  get "service/arbitral_tribunal"
=end
  resources :static_texts

  resources :service

  devise_for :users

  resources :contests

  resources :departments

  resources :people

  resources :events

  resources :previews

  get "about/index"
  get "about/info"

  get "administration/index"
  get "administration/localization"
  get "members_tpp/how_become"
  get "members_tpp/docs"
  resources :news
  mount Ckeditor::Engine => '/ckeditor'

  get "service/f_e_activity"

   root 'about#index'

   get 'administration/index', as: 'user_root'

  

end

app/models/contest.rb
class Contest < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/header_image.rb
class HeaderImage < ActiveRecord::Base

  do_not_validate_attachment_file_type :avatar
  has_attached_file :avatar, :styles => { :medium => "1076x274>", :thumb => "100x100>" }

end

app/models/image_album.rb
class ImageAlbum < ActiveRecord::Base
  has_many :image_gallery
end

app/models/image_gallery.rb
class ImageGallery < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/models/localization.rb
class Localization < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base

end

app/models/person.rb
class Person < ActiveRecord::Base

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/preview.rb
class Preview < ActiveRecord::Base
end

app/models/quotation.rb
class Quotation < ActiveRecord::Base
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "News"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/service_list.rb
class ServiceList < ActiveRecord::Base
end

app/models/static_text.rb
class StaticText < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_contest, only: [:show, :edit, :update, :destroy]

  # GET /contests
  # GET /contests.json
  def index
    @contests = Contest.all

    render :layout =>  "../administration/index"

  end

  # GET /contests/1
  # GET /contests/1.json
  def show

    render :layout =>  "../administration/index"

  end

  # GET /contests/new
  def new
    @contest = Contest.new

    render :layout =>  "../administration/index"

  end

  # GET /contests/1/edit
  def edit

    render :layout =>  "../administration/index"

  end

  # POST /contests
  # POST /contests.json
  def create
    @contest = Contest.new(contest_params)

    respond_to do |format|
      if @contest.save
        format.html { redirect_to @contest, notice: 'Contest was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contest }
      else
        format.html { render action: 'new' }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contests/1
  # PATCH/PUT /contests/1.json
  def update
    respond_to do |format|
      if @contest.update(contest_params)
        format.html { redirect_to @contest, notice: 'Contest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contests/1
  # DELETE /contests/1.json
  def destroy
    @contest.destroy
    respond_to do |format|
      format.html { redirect_to contests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contest
      @contest = Contest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contest_params
      params.require(:contest).permit(:title, :small_text, :text)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/views/contests/_form.html.erb
<%= form_for(@contest) do |f| %>
  <% if @contest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contest.errors.count, "error") %> prohibited this contest from being saved:</h2>

      <ul>
      <% @contest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Заголовок %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :Превью %><br>
    <%= f.text_field :small_text %>
  </div>
    <div class="field">
      <%= f.label :Аватар %><br>
      <%=f.file_field :avatar %>
    </div>
  <div class="field">
    <%= f.label :Текст %><br>
    <%= f.cktext_area :text, :as => :ckeditor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contests/edit.html.erb
<h1>Editing contest</h1>

<%= render 'form' %>

<%= link_to 'Show', @contest %> |
<%= link_to 'Back', contests_path %>

app/views/contests/index.html.erb
<h1>Список конкурсов</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Заголовок</th>
      <th>Превью</th>
      <th>Текст</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contests.each do |contest| %>
      <tr>
        <td><%= contest.title %></td>
        <td><%= contest.small_text %></td>
        <td><%= contest.text %></td>
        <td><%= link_to 'Показать', contest %></td>
        <td><%= link_to 'Изменить', edit_contest_path(contest) %></td>
        <td><%= link_to 'Удалить', contest, method: :delete, data: { confirm: 'Вы уверенны?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Создать', new_contest_path %>

app/views/contests/new.html.erb
<h1>New contest</h1>

<%= render 'form' %>

<%= link_to 'Back', contests_path %>

app/views/contests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @contest.title %>
</p>

<p>
  <strong>Аватар:</strong>
  <img src="<%= @person.avatar.url(:medium) %>"/>
</p>

<p>
  <strong>Small text:</strong>
  <%= @contest.small_text %>
</p>

<p>
  <strong>Text:</strong>
  <%= @contest.text %>
</p>

<%= link_to 'Edit', edit_contest_path(@contest) %> |
<%= link_to 'Back', contests_path %>