config/routes.rb
Tpprd::Application.routes.draw do

  resources :header_images

  resources :hrader_images

  resources :quotations

  resources :image_albums

  resources :image_galleries

  post '/rate' => 'rater#create', :as => 'rate'
  resources :service_lists

  get "navigations/news_show"
  get "navigations/news"
  get "navigations/gallery"
  get "navigations/albums"
  get "navigations/previews"
  get "navigations/preview_show"
  get "navigations/events"
  get "navigations/event_show"
  get "navigations/quotations"
  get "navigations/quotations_show"

=begin
  get "service/f_t_contracts"
  get "service/b_e_a_t"
  get "service/e_i_c_c"
  get "service/i_and_i"
  get "service/mediation"
  get "service/org_department"
  get "service/translations"
  get "service/legal_support"
  get "service/arbitral_tribunal"
=end
  resources :static_texts

  resources :service

  devise_for :users

  resources :contests

  resources :departments

  resources :people

  resources :events

  resources :previews

  get "about/index"
  get "about/info"

  get "administration/index"
  get "administration/localization"
  get "members_tpp/how_become"
  get "members_tpp/docs"
  resources :news
  mount Ckeditor::Engine => '/ckeditor'

  get "service/f_e_activity"

   root 'about#index'

   get 'administration/index', as: 'user_root'

  

end

app/models/contest.rb
class Contest < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/header_image.rb
class HeaderImage < ActiveRecord::Base

  do_not_validate_attachment_file_type :avatar
  has_attached_file :avatar, :styles => { :medium => "1076x274>", :thumb => "100x100>" }

end

app/models/image_album.rb
class ImageAlbum < ActiveRecord::Base
  has_many :image_gallery
end

app/models/image_gallery.rb
class ImageGallery < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/models/localization.rb
class Localization < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base

end

app/models/person.rb
class Person < ActiveRecord::Base

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/preview.rb
class Preview < ActiveRecord::Base
end

app/models/quotation.rb
class Quotation < ActiveRecord::Base
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "News"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/service_list.rb
class ServiceList < ActiveRecord::Base
end

app/models/static_text.rb
class StaticText < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  before_action :set_quotation, only: [:show, :edit, :update, :destroy]

  # GET /quotations
  # GET /quotations.json
  def index
    @quotations = Quotation.all
  end

  # GET /quotations/1
  # GET /quotations/1.json
  def show
  end

  # GET /quotations/new
  def new
    @quotation = Quotation.new
  end

  # GET /quotations/1/edit
  def edit
  end

  # POST /quotations
  # POST /quotations.json
  def create
    @quotation = Quotation.new(quotation_params)

    respond_to do |format|
      if @quotation.save
        format.html { redirect_to @quotation, notice: 'Quotation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @quotation }
      else
        format.html { render action: 'new' }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotations/1
  # PATCH/PUT /quotations/1.json
  def update
    respond_to do |format|
      if @quotation.update(quotation_params)
        format.html { redirect_to @quotation, notice: 'Quotation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotations/1
  # DELETE /quotations/1.json
  def destroy
    @quotation.destroy
    respond_to do |format|
      format.html { redirect_to quotations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quotation
      @quotation = Quotation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quotation_params
      params.require(:quotation).permit(:title, :date, :text)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/views/quotations/_form.html.erb
<%= form_for(@quotation) do |f| %>
  <% if @quotation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quotation.errors.count, "error") %> prohibited this quotation from being saved:</h2>

      <ul>
      <% @quotation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotations/edit.html.erb
<h1>Editing quotation</h1>

<%= render 'form' %>

<%= link_to 'Show', @quotation %> |
<%= link_to 'Back', quotations_path %>

app/views/quotations/index.html.erb
<h1>Listing quotations</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Text</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @quotations.each do |quotation| %>
      <tr>
        <td><%= quotation.title %></td>
        <td><%= quotation.date %></td>
        <td><%= quotation.text %></td>
        <td><%= link_to 'Show', quotation %></td>
        <td><%= link_to 'Edit', edit_quotation_path(quotation) %></td>
        <td><%= link_to 'Destroy', quotation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quotation', new_quotation_path %>

app/views/quotations/new.html.erb
<h1>New quotation</h1>

<%= render 'form' %>

<%= link_to 'Back', quotations_path %>

app/views/quotations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @quotation.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @quotation.date %>
</p>

<p>
  <strong>Text:</strong>
  <%= @quotation.text %>
</p>

<%= link_to 'Edit', edit_quotation_path(@quotation) %> |
<%= link_to 'Back', quotations_path %>