config/routes.rb
Tpprd::Application.routes.draw do

  resources :header_images

  resources :hrader_images

  resources :quotations

  resources :image_albums

  resources :image_galleries

  post '/rate' => 'rater#create', :as => 'rate'
  resources :service_lists

  get "navigations/news_show"
  get "navigations/news"
  get "navigations/gallery"
  get "navigations/albums"
  get "navigations/previews"
  get "navigations/preview_show"
  get "navigations/events"
  get "navigations/event_show"
  get "navigations/quotations"
  get "navigations/quotations_show"

=begin
  get "service/f_t_contracts"
  get "service/b_e_a_t"
  get "service/e_i_c_c"
  get "service/i_and_i"
  get "service/mediation"
  get "service/org_department"
  get "service/translations"
  get "service/legal_support"
  get "service/arbitral_tribunal"
=end
  resources :static_texts

  resources :service

  devise_for :users

  resources :contests

  resources :departments

  resources :people

  resources :events

  resources :previews

  get "about/index"
  get "about/info"

  get "administration/index"
  get "administration/localization"
  get "members_tpp/how_become"
  get "members_tpp/docs"
  resources :news
  mount Ckeditor::Engine => '/ckeditor'

  get "service/f_e_activity"

   root 'about#index'

   get 'administration/index', as: 'user_root'

  

end

app/models/contest.rb
class Contest < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/header_image.rb
class HeaderImage < ActiveRecord::Base

  do_not_validate_attachment_file_type :avatar
  has_attached_file :avatar, :styles => { :medium => "1076x274>", :thumb => "100x100>" }

end

app/models/image_album.rb
class ImageAlbum < ActiveRecord::Base
  has_many :image_gallery
end

app/models/image_gallery.rb
class ImageGallery < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/models/localization.rb
class Localization < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base

end

app/models/person.rb
class Person < ActiveRecord::Base

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/preview.rb
class Preview < ActiveRecord::Base
end

app/models/quotation.rb
class Quotation < ActiveRecord::Base
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "News"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/service_list.rb
class ServiceList < ActiveRecord::Base
end

app/models/static_text.rb
class StaticText < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/previews_controller.rb
class PreviewsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_preview, only: [:show, :edit, :update, :destroy]

  # GET /previews
  # GET /previews.json
  def index
    @previews = Preview.all

    render :layout =>  "../administration/index"

  end

  # GET /previews/1
  # GET /previews/1.json
  def show

    render :layout =>  "../administration/index"

  end

  # GET /previews/new
  def new

    @preview = Preview.new

    render :layout =>  "../administration/index"

  end

  # GET /previews/1/edit
  def edit

    render :layout =>  "../administration/index"

  end

  # POST /previews
  # POST /previews.json
  def create
    @preview = Preview.new(preview_params)

    respond_to do |format|
      if @preview.save
        format.html { redirect_to @preview, notice: 'Preview was successfully created.' }
        format.json { render action: 'show', status: :created, location: @preview }
      else
        format.html { render action: 'new' }
        format.json { render json: @preview.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /previews/1
  # PATCH/PUT /previews/1.json
  def update
    respond_to do |format|
      if @preview.update(preview_params)
        format.html { redirect_to @preview, notice: 'Preview was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @preview.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /previews/1
  # DELETE /previews/1.json
  def destroy
    @preview.destroy
    respond_to do |format|
      format.html { redirect_to previews_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preview
      @preview = Preview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def preview_params
      params.require(:preview).permit(:title, :date, :text, :small_text)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/previews_helper.rb
module PreviewsHelper
end

app/views/previews/_form.html.erb
<%= form_for(@preview) do |f| %>
    <% if @preview.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@preview.errors.count, "error") %> prohibited this preview from being saved:</h2>

          <ul>
            <% @preview.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :Заголовок %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :Дата %><br>
      <%= f.date_select :date %>
    </div>

    <div class="field">
      <%= f.label :Превью %><br>
      <%= f.text_field :small_text %>
    </div>
    <div class="field">
      <%= f.label :Текс %><br>
      <%= f.cktext_area :text, :as => :ckeditor %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/previews/edit.html.erb
<h1>Editing preview</h1>

<%= render 'form' %>

<%= link_to 'Show', @preview %> |
<%= link_to 'Back', previews_path %>

app/views/previews/index.html.erb
<h1>Список анонсов</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Заголовок</th>
      <th>Дата</th>
      <th>Текст</th>
      <th>Превью</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @previews.each do |preview| %>
      <tr>
        <td><%= preview.title %></td>
        <td><%= preview.date %></td>
        <td><%= preview.text.truncate(100)  %></td>
        <td><%= preview.small_text.truncate(100) %></td>
        <td><%= link_to 'Показать', preview %></td>
        <td><%= link_to 'Изменить', edit_preview_path(preview) %></td>
        <td><%= link_to 'Удалить', preview, method: :delete, data: { confirm: 'Вы уверенны?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Создать', new_preview_path %>

app/views/previews/new.html.erb
<h1>New preview</h1>

<%= render 'form' %>

<%= link_to 'Back', previews_path %>

app/views/previews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @preview.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @preview.date %>
</p>

<p>
  <strong>Text:</strong>
  <%= @preview.text.html_safe %>
</p>

<p>
  <strong>Small text:</strong>
  <%= @preview.small_text %>
</p>

<%= link_to 'Edit', edit_preview_path(@preview) %> |
<%= link_to 'Back', previews_path %>